skylersaleh/SkyEmu

CMakeLists.txt
src/main.c
src/tinyfiledialogs/README.txt
src/tinyfiledialogs/extras_dll_cs_lua_fortran/LUA_plugin.tinyfiledialogs.cpp
src/tinyfiledialogs/extras_dll_cs_lua_fortran/fortran/compile_and_link.txt
src/tinyfiledialogs/extras_dll_cs_lua_fortran/fortran/ftinyopen.F90
src/tinyfiledialogs/extras_dll_cs_lua_fortran/fortran/main2.F90
src/tinyfiledialogs/extras_dll_cs_lua_fortran/fortran/tinyopen.c
src/tinyfiledialogs/extras_dll_cs_lua_fortran/tinyfiledialogsTest.cs
src/tinyfiledialogs/extras_dll_cs_lua_fortran/tinyfiledialogs_dll_mingw-32.bat
src/tinyfiledialogs/extras_dll_cs_lua_fortran/tinyfiledialogs_dll_mingw-w64-720.bat
src/tinyfiledialogs/extras_dll_cs_lua_fortran/tinyfiledialogs_dll_mingw-w64-810.bat
src/tinyfiledialogs/extras_dll_cs_lua_fortran/tinyfiledialogs_dylib.txt
src/tinyfiledialogs/hello.c
src/tinyfiledialogs/hello_wchar_t.c
src/tinyfiledialogs/more_dialogs/tinyfd_moredialogs.c
src/tinyfiledialogs/more_dialogs/tinyfd_moredialogs.h
src/tinyfiledialogs/tinyfiledialogs.c
src/tinyfiledialogs/tinyfiledialogs.h

This allows ROMs to be selected in the desktop builds by clicking the load ROM button like the web based builds can.

File selection dialogs for desktop platforms

---

.github/workflows/deploy_web.yml

Deploy commits that are not in main to another location on the web server

【GitHub】Deploy commits that are not in main to another location on the web server

---

src/main.c

This pull request is tracking some improvements being worked on for sav and bios management on the web builds of SkyEmu.

Web sav and bios loading improvements

---

src/gb.h

Adds emulation for the linear-feedback shift register that is used to generate pseudeorandom noise for the noise channel in the Game Boy's sound processor.

【GB】Add LFSR for noise channel

---

src/main.c

Fix web cheats with hex numbers > 0x7FFF'FFFF

---

src/main.c

by setting the mode to RESET, reset_core would eventually be ran which would simply load the rom again and set the mode to RUN.

Don't load roms twice

---

src/sb_types.h

Close file stream

---

src/sb_types.h

fixes #337 
one less point in #334
there are other bugs in code, at least now you are no longer stuck in /home

[Frontend] sb_parent_path: fix bad logic and minor clean up

---

.github/workflows/deploy_mac.yml

Experiments to fix the errors in the mac-os-builder

Fix mac os builder

---

README.md

Removes these blue underline thingies

Remove blue underlines in readme

---

src/main.c

used a separate array as the original one is used to reset and to not lose the original order
Fixes part of #353

Add sort recent games button

---

src/main.c

Don't allow tabbing into volume slider

---

src/cloud.cpp
src/cloud.h
src/main.c

Moved awaiting_login/logout stuff to cloud.cpp, removed unused username variable in cloud_state, removed unnecessary function parameters in google_get_user_data and google_cloud_drive_init, made sure a failed login doesn't get stuck in "pending_login" mode

More cloud cleanups

---

src/cloud.cpp
src/main.c

further simplified cloud_state struct, removed some code dupe in cloud.cpp (thread starting, pending logout checking), made func names more consistent and a bit of formatting

Reduce code duplication in cloud.cpp

---

README.md

The Polish localisation has been merged, so I added the change to the README.

Add Polish to list of locales in README.md

---

src/localization.c

Add Polish to list of Unicode languages

---

src/localization.c

Add Danish to list of Unicode languages

---

.github/workflows/deploy_web.yml

These were added to make it so the branch gets deployed to my website for testing but we don't need them in upstream

Cleanup leftover changes in deploy_web.yml

---

src/main.c

Continuation of https://github.com/skylersaleh/SkyEmu/pull/354

Fixed up version of "Remove game from recently played list" pull request

---

src/main.c

Rebase of this PR to latest code base https://github.com/skylersaleh/SkyEmu/pull/355
PR sent from my account to allow testing the web build

Continuation of Add Export Save States Button PR

---

.github/workflows/deploy_web.yml

Hopefully this yields to better code generation for web builds.

Upgrade emsdk
